"""add chunk embedding

Revision ID: b7f147953f83
Revises: fca7071916d2
Create Date: 2026-10-07 15:25:29.109137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# 오류로 인해 임의로 추가함 by. claude _10.07
import pgvector.sqlalchemy 


# revision identifiers, used by Alembic.
revision: str = 'b7f147953f83'
down_revision: Union[str, Sequence[str], None] = 'fca7071916d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chunks', 'embedding')
    # ### end Alembic commands ###
